config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "homes#index"
  resources :users, only: [:show, :index] do
    resources :products do
      resources :comments, only: [:create, :edit, :update, :destroy]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :c_description, presence: true, allow_blank: false
  belongs_to :user
  belongs_to :product
  default_scope -> { order(updated_at: :desc)}
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many_attached :images
  validates :p_name, presence: true
  validates :p_price, presence: true
  validates :p_description, presence: true
  validates :images, presence: true

  def serial_number
    "Dev-%.6d" % self.id
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :products, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one_attached :image
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :address, :phone_number, :image, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :address, :phone_number, :image, :email, :password, :current_password) }
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :require_user
  before_action :set_product

  def create
    @comment = @product.comments.build(comment_params)
    @comment.user = current_user
    if @comment.save
      ActionCable.server.broadcast "comments", render(partial: 'comments/comment', object: @comment)
      # flash[:success] = "Comment was created successfully"
      # redirect_to user_product_path(current_user,@product)
    else
      flash[:danger] = "Comment was not created"
      redirect_to :back
    end
  end

  def edit
    @comment = @product.comments.find_by(id: params[:id])
  end

  def update
    @comment = @product.comments.find_by(id: params[:id])
    @comment.update(comment_params)
  end

  def destroy
    @comment = @product.comments.find_by(id: params[:id])
    @comment.destroy
  end

  private

  def comment_params
    params.require(:comment).permit(:c_description)
  end

  def set_product
    @product = Product.find_by(id: params[:product_id])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # before_action :require_same_user, except: [:show, :index]

  def index
    @products = current_user.products.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user_id = current_user.id
    if @product.save
      flash[:success]= "Your Product has been created successfully!"
      redirect_to user_products_path
    else
      render 'new'
    end
  end

  def edit
    
  end

  def update
    if @product.update(product_params)
      flash[:success]="Your has been updated successfully!"
      redirect_to user_product_path(current_user, @product)
    else
      render 'edit'
    end
  end

  def show
    @comment = Comment.new
    @comments = @product.comments.all
  end

  def destroy
    @product.destroy
    flash[:success]= "Product has been deleted succesfully!"
    redirect_to user_products_path
  end

  private
  def product_params
    params.require(:product).permit(:p_name, :p_price, :p_description, :user_id, images: [])
  end

  def set_product
    @product = Product.find(params[:id])
  end

  # def require_same_user
  #   if (current_user.id != params[:user_id].to_i)
  #     flash[:danger] = "Only admin user can perform this action."
  #     redirect_to root_path
  #   end
  # end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div class="row" id="comment-<%= comment.id %>">
  <div class="col-md-2">
    <section class="user_info center">
      <%= image_tag((comment.user.image), class: "comment-user-image") %>
    </section>
  </div>
  <div class="col-md-8 well">
    <p><%= comment.c_description %></p>
    <% if user_signed_in? && current_user == comment.user %>
      <p class="pull-right">  <%= link_to "Delete", user_product_comment_path(comment.user,@product,comment), method: :delete,
        remote: true, data: { confirm: "Are you sure you want to delete?" } %></p>
      <div id="edit-comment-<% comment.id %>">
        <p class="pull-right"><%= link_to "Edit", edit_user_product_comment_path(current_user,@product,comment), remote: true %></p>
      </div
    <% end %>
    <p>
      <span class="quiet"><small>Created: <%= time_ago_in_words(comment.created_at) %> ago by <%= comment.user.name %></small></span>
    </p>
  </div>
</div>

app/views/comments/_comments.html.erb
<% comments.each do |comment| %>
  <%= render(partial: 'comments/comment', object: comment) %>
<% end %>

app/views/comments/_edit_form.html.erb
<%= form_for([current_user, @product, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
  <div class="row">
    <div class="col-md-2">
      <section class="user_info center">
        <%= image_tag((@comment.user.image), class: "comment-user-image") %>
      </section>
    </div>
    <div class="col-md-8 well">
      <p><%= f.text_area :c_description, autofocus: true, autocomplete: "c_description", class: "form-control" %></p>
      <p><%= f.submit "Update", class: "button-design" %> <%= link_to "Back", :back, class: "btn button-design" %></p>
    </div>
  </div>
<% end %>

app/views/comments/destroy.js.erb
$('#comment-<% @comment.id %>').html('');

app/views/comments/edit.js.erb
$("#comment-<%= @comment.id %>").replaceWith('<%= j render "edit_form" %>');

app/views/comments/update.js.erb
$("#comment-<%= @comment.id %>").replaceWith('<%= j render(partial: "comments/comment", object: @comment) %>')

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-dark background-navbar-color">
  <!-- <a class="navbar-brand" href="#"><strong>Navbar</strong></a> -->
  <%= link_to "Logo", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <!-- <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a> -->
        <%= link_to "Add Products", new_user_product_path(current_user, @product), class: "nav-link" %>
      </li>
      <% end %>
      <li class="nav-item">
        <a class="nav-link" href="#">Profile</a>
      </li>
      <li class="nav-item">
        <% if user_signed_in? %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        <% else %>
          <%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demoapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "layouts/navigation" %>
    <%= render "layouts/alerts"  %>
    <%= yield %>
  </body>
</html>

app/views/products/_form.html.erb
<%= form_for [current_user,@product] do |f| %>
  <div class="form">
    <% if @product.p_name.nil? %>
      <h2>Add Product</h2>
    <% else %>
      <h2>Edit Product</h2>
    <% end %>
    <label>
      <%= f.text_field :p_name, autofocus: true, autocomplete: 'p_name', placeholder: 'Product Name', class: 'input' %>
      <div class="line-box">
        <div class="line"></div>
      </div>
    </label><br />
    <label>
      <%= f.text_field :p_price, autofocus: true, autocomplete: 'p_price', placeholder: "Product's Price", class: 'input' %>
      <div class="line-box">
        <div class="line"></div>
      </div>
    </label><br />
    <label>
      <%= f.text_area :p_description, autofocus: true, autocomplete: "p_description", placeholder: "Product's description", class: 'input' %>
      <div class="line-box">
        <div class="line"></div>
      </div>
    </label><br />
    <label>
      <%= f.label :images %>
      <%= f.file_field :images, multiple: true %>
    </label><br /><br />
    <div class="actions">
      <%= f.submit(@product.new_record? ? "Create my account" : "Update my account", class: "btn button-design") %> <%= link_to "Back", :back, class: "btn button-design" %>
    </div>
  </div>
<% end %>

app/views/products/edit.html.erb
<%= render 'form' %>

app/views/products/index.html.erb
<% current_user.products.each do |product| %>
  <%= product.p_name %>
  <%= product.p_price %>
  <%= product.p_description %>
  <% product.images.each do |image| %>
    <%= image_tag(image) %>
  <% end %>
<% end %>

app/views/products/new.html.erb
<%= render 'form' %>

app/views/products/show.html.erb
<div class="container-fluid">
  <div class="content-wrapper">
		<div class="item-container">
			<div class="container">
				<div class="col-md-12">
					<div class="product col-md-3 service-image-left">
						<center>
              <%= image_tag((@product.images.first), class: "img", id: "item-display") %>
						</center>
					</div>
					<div class="container service1-items col-sm-2 col-md-2 pull-left">
						<center>
							<a id="item-1" class="service1-item">
                <%= image_tag((@product.images.second), class: "img") %>
              </a>
							<a id="item-2" class="service1-item">
                <%= image_tag((@product.images.third), class: "img") %>
              </a>
						</center>
					</div>
				</div>
				<div class="col-md-7">
					<div class="product-title"><%= @product.p_name %></div>
					<div class="product-desc"><%= @product.p_description.split('.').first %></div>
					<hr>
					<div class="product-price"><%= @product.p_price %></div>
					<div class="product-stock"></div>
					<hr>
					<div class="btn-group cart">
						<button type="button" class="btn btn-success">
							Add to cart
						</button>
					</div>
				</div>
			</div>
		</div>
		<div class="container-fluid pull-left">
			<div class="col-md-12 product-info">
				<ul id="myTab" class="nav nav-tabs nav_tabs">
					<li class="active"><a href="#service-one" data-toggle="tab" class="button-design">DESCRIPTION</a></li>
					<li><a href="#service-two" data-toggle="tab" class="button-design">Comments</a></li>
				</ul>
				<div id="myTabContent" class="tab-content">
					<div class="tab-pane fade in active" id="service-one">
						<section class="container product-info">
						  <%= @product.p_description %>
							<h3><%= @product.p_name %>'s Features</h3>
							<% @product.p_description.split('.').each do |feature| %>
                <li><%= feature %>.</li>
              <% end %>
						</section>
					</div>
					<div class="tab-pane fade" id="service-two">
						<section class="container">
              <% if user_signed_in? %>
                <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                    <%= form_for([current_user, @product, @comment], remote: true, :html => {class: "form-horizontal", role: "form"}) do |f| %>
                      <div class="form-group">
                        <br>
                        <div class="col-md-8">
                          <%= f.text_area :c_description, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
                        </div>
                      </div>
                      <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                          <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge button-design" %>
                        </div>
                      </div>
                    <% end %>
                    <hr />
                  </div>
                </div>
              <% end %>
              <% if @product.comments != 0 %>
                <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                    <br>
                    <% if !user_signed_in?%>
                      <h5>For commenting, you have to <%= link_to 'Sign in', new_user_session_path %> first. </h5>
                      <hr />
                    <% end %>
                    <div id="messages">
                      <%= render partial: 'comments/comments', object: @comments %>
                    </div>
                  </div>
                </div>
              <% else %>
                <div class="row">
                  <div class="col-md-8 col-md-offset-2">
                    <h3>No Comments Yet!</h3>
                  </div>
                </div>
              <% end %>
            </section>
					</div>
				</div>
				<hr>
			</div>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container-fluid well span6">
  <div align="center">
    <div class="row-fluid">
      <div class="span2" >
        <%= image_tag((current_user.image), class:"avatar img-circle img-thumbnail") %>
      </div>
      <div class="span8">
        <h3>Name: <%= current_user.name %></h3>
        <h6>Email: <%= current_user.email %></h6>
        <h6>Phone Number: <%= current_user.phone_number %></h6>
        <h6>Address: <%= current_user.address %></h6>
      </div>
      <div class="span2">
        <%= link_to "Edit your profile", edit_user_registration_path, class: "btn button-design" %>
        <%= link_to "Back", :back , class: "button-design btn" %>
      </div>
    </div>
  </div>
</div>